# Generated by Django 5.2 on 2026-06-26 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('FREE', 'Plan Gratuit'), ('PRO', 'Plan Professionnel'), ('ENTERPRISE', 'Plan Entreprise')], help_text='Le type de plan concerné par cette configuration', max_length=20, unique=True)),
                ('max_devices', models.PositiveIntegerField(default=1, help_text='Nombre maximum de PC autorisés pour ce plan')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Durée par défaut de la souscription en jours (ex: 30 pour 1 mois, 365 pour 1 an)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('FREE', 'Plan Gratuit'), ('PRO', 'Plan Professionnel'), ('ENTERPRISE', 'Plan Entreprise')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('CANCELED', 'Annulé (Finit la période en cours)'), ('EXPIRED', 'Expiré'), ('PAST_DUE', 'Impayé')], default='ACTIVE', max_length=20)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
